### ISSUE TITLE
Update NEAR tokens required for staking pool storage

### ISSUE THREAD

**Issue by janewang** [referencedev/staking-farm#10]
Could you please update this constant (https://github.com/referencedev/staking-farm/blob/master/staking-factory/src/lib.rs#L12 ) to reduce the number of NEAR tokens required for storage.

I think it's 4 NEAR max now, not 30.  As the fee is not refundable to validators, would be good to update it. Also some validators (and future chunk only producers) are finding the 30 NEAR too expensive at the moment. Thanks!

**Comment by referencedev** [comment]
Done
